---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2 
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: api-container
        image: public.ecr.aws/d3k6a8t8/simple-springboot-api:latest
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.25"
            memory: "128Mi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: app
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32000
